service: login-service
frameworkVersion: "3"

provider:
    name: aws
    runtime: python3.8
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - dynamodb:PutItem
                  Resource: "arn:aws:dynamodb:us-east-1:*:table/user_sessions"

functions:
    login:
        handler: handler.login
        events:
            - httpApi:
                  path: /login
                  method: post

plugins:
    - serverless-offline
    - serverless-dotenv-plugin
    - serverless-python-requirements
